use_frameworks!

target 'ALWCollectionViewLayout_Example' do
  pod 'ALWCollectionViewLayout', :path => '../'

  target 'ALWCollectionViewLayout_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
